### ISSUE TITLE
Open Weather API key should be private

### ISSUE THREAD

**Issue by nleeper** [Acesonnall/Grabbing-The-Weather#2]
The API key for OpenWeather is included in this repo

https://github.com/Acesonnall/Grabbing-The-Weather/blob/c9e76e6032b1b662efe668466bb8a2e857733708/app/routes/routes.js#L73

Please alter this repo to remove the key.

**Comment by Acesonnall** [comment]
Fixed.

https://github.com/Acesonnall/Grabbing-The-Weather/blob/dd46314fd171d8effdd622e9c728878a4c34ab74/app.js#L43

**Comment by nleeper** [comment]
This looks good, environment variables are always a good choice for protecting keys or secrets 👍
