### ISSUE TITLE
Lowercase city cannot be found

### ISSUE THREAD

**Issue by nleeper** [Acesonnall/Grabbing-The-Weather#3]
If I enter "des moines" in the city field and "United States" in the country field, I get the message "Location not supported". The application should be able to find cities that are supplied in any case, i.e Des Moines, des moines, des Moines, dEs MOInes, etc

**Comment by Acesonnall** [comment]
Fixed:

https://github.com/Acesonnall/Grabbing-The-Weather/blob/dd46314fd171d8effdd622e9c728878a4c34ab74/app/routes/routes.js#L25

**Comment by nleeper** [comment]
This works. Another way would be to just lowercase the comparison in weather.js on the city name:

https://github.com/Acesonnall/Grabbing-The-Weather/blob/dd46314fd171d8effdd622e9c728878a4c34ab74/app/weather/weather.js#L81

Lowercasing wouldn't require a new method, but could be slightly slower depending on how many iterations you made through the loop. Either way, good job 👍
