### ISSUE TITLE
city.list.json file is loaded on every request

### ISSUE THREAD

**Issue by nleeper** [Acesonnall/Grabbing-The-Weather#4]
Currently, the city.list.json file is loaded on every request:

https://github.com/Acesonnall/Grabbing-The-Weather/blob/c9e76e6032b1b662efe668466bb8a2e857733708/app/routes/routes.js#L54

This file should only be loaded once at startup or on first request.

**Comment by Acesonnall** [comment]
Fixed.

https://github.com/Acesonnall/Grabbing-The-Weather/blob/dd46314fd171d8effdd622e9c728878a4c34ab74/app.js#L43

**Comment by nleeper** [comment]
This looks good 👍
